language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"

install:
  - "meteor add mike:mocha-package"

script:
  - "meteor test-packages --velocity --driver-package respondly:test-reporter ./"