language: node_js
node_js:
  - "0.10"

install:
  - "curl https://install.meteor.com | /bin/sh"
  - "meteor add mike:mocha-package"

script:
  - "meteor test-packages --velocity --driver-package respondly:test-reporter ./"