language: node_js
node_js:
  - "0.10"

install:
  - "curl -L https://install.meteor.com | /bin/sh"

script:
  - "echo $PATH"
  - "export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  - "meteor add mike:mocha-package"
  - "meteor test-packages --velocity --driver-package respondly:test-9 reporter ./"